apiVersion: v1
kind: ConfigMap

metadata:
  name: movie-config
  namespace: movie-ticket

data:
  REACT_APP_API_BASE_URL: "http://backend-service:5000"
  REACT_APP_NAME: "🎬 Movie Ticket Booking"
  REACT_APP_ENVIRONMENT: "Development"