apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: movie-developer-role
  namespace: movie-ticket
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - get
      - list