apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gp3-test-pvc
  namespace: movie-ticket
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi